// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrPnd9sXp6EFws06ttz338iLJBmtl_W_4',
    appId: '1:533916619628:web:435a9738cc0ab8c633d949',
    messagingSenderId: '533916619628',
    projectId: 'padizdoctor-fyp-6820b',
    authDomain: 'padizdoctor-fyp-6820b.firebaseapp.com',
    storageBucket: 'padizdoctor-fyp-6820b.firebasestorage.app',
    measurementId: 'G-HV9L04VVGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxcZg9ync1dwoMdQ0JWoV1y13d4vnFnJo',
    appId: '1:533916619628:android:991c2deda4c3df8833d949',
    messagingSenderId: '533916619628',
    projectId: 'padizdoctor-fyp-6820b',
    storageBucket: 'padizdoctor-fyp-6820b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhKxhXBIQ6WXJy9dI7_52wVL9HBXYxiCM',
    appId: '1:533916619628:ios:913ab2373bc3818633d949',
    messagingSenderId: '533916619628',
    projectId: 'padizdoctor-fyp-6820b',
    storageBucket: 'padizdoctor-fyp-6820b.firebasestorage.app',
    iosClientId: '533916619628-9a0hh99pt17fgctmrone29g12a1no7gs.apps.googleusercontent.com',
    iosBundleId: 'com.example.padizdoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhKxhXBIQ6WXJy9dI7_52wVL9HBXYxiCM',
    appId: '1:533916619628:ios:913ab2373bc3818633d949',
    messagingSenderId: '533916619628',
    projectId: 'padizdoctor-fyp-6820b',
    storageBucket: 'padizdoctor-fyp-6820b.firebasestorage.app',
    iosClientId: '533916619628-9a0hh99pt17fgctmrone29g12a1no7gs.apps.googleusercontent.com',
    iosBundleId: 'com.example.padizdoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrPnd9sXp6EFws06ttz338iLJBmtl_W_4',
    appId: '1:533916619628:web:2c1b48e35d5ad75f33d949',
    messagingSenderId: '533916619628',
    projectId: 'padizdoctor-fyp-6820b',
    authDomain: 'padizdoctor-fyp-6820b.firebaseapp.com',
    storageBucket: 'padizdoctor-fyp-6820b.firebasestorage.app',
    measurementId: 'G-K6VGYR2CBR',
  );

}